export const PROJECTS = [
  {
    id: 1,
    title: 'NovaMind AI Dashboard',
    category: 'AI Tools',
    description: 'Real-time AI analytics dashboard with LLM integration and live data visualization.',
    techStack: ['React', 'Python', 'OpenAI API', 'Tailwind'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
    imageAlt: 'NovaMind AI Dashboard — React and OpenAI powered analytics by jabx_fx',
    liveLink: '#', // TODO: Update with actual live URL when ready
    caseLink: '#', // TODO: Update with actual case study URL when ready
    metrics: { label: '+68% user retention', highlight: true },
    featured: true,
    size: 'large',
  },
  {
    id: 2,
    title: 'Flux Design System',
    category: 'Design',
    description: 'Enterprise-grade Figma design system with 200+ components and token sets.',
    techStack: ['Figma', 'Token Studio', 'Storybook'],
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2000&auto=format&fit=crop',
    imageAlt: 'Flux Design System — 200+ component Figma library by jabx_fx',
    liveLink: '#',
    caseLink: '#',
    metrics: { label: '200+ Components', highlight: false },
    featured: false,
    size: 'tall',
  },
  {
    id: 3,
    title: 'Launchpad SaaS Landing',
    category: 'Development',
    description: 'High-conversion SaaS landing page. A/B tested. 40% improvement in demo signups.',
    techStack: ['React', 'Framer Motion', 'Tailwind'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop',
    imageAlt: 'Launchpad SaaS Landing Page — +40% demo signup conversion by jabx_fx',
    liveLink: '#',
    caseLink: '#',
    metrics: { label: '+40% demo signups', highlight: true },
    featured: false,
    size: 'normal',
  },
  {
    id: 4,
    title: 'Promptly — AI Writing Tool',
    category: 'AI Tools',
    description: 'Browser-based AI writing assistant with custom prompt chains and export system.',
    techStack: ['React', 'Claude API', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop',
    imageAlt: 'Promptly AI Writing Tool — custom prompt chain app by jabx_fx',
    liveLink: '#',
    caseLink: '#',
    metrics: { label: '1,200+ active users', highlight: true },
    featured: false,
    size: 'normal',
  },
  {
    id: 5,
    title: 'Arc Portfolio Framework',
    category: 'Design',
    description: 'Reusable portfolio framework for creative developers. Used by 30+ freelancers.',
    techStack: ['Figma', 'React', 'Tailwind'],
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=2055&auto=format&fit=crop',
    imageAlt: 'Arc Portfolio Framework — used by 30+ developers, designed by jabx_fx',
    liveLink: '#',
    caseLink: '#',
    metrics: { label: '30+ deployments', highlight: false },
    featured: false,
    size: 'normal',
  },
  {
    id: 6,
    title: 'Kova E-commerce UI',
    category: 'Development',
    description: 'Fashion e-commerce UI with editorial grid layout, cart system, and checkout flow.',
    techStack: ['React', 'Tailwind', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=2070&auto=format&fit=crop',
    imageAlt: 'Kova E-commerce UI — fashion editorial layout built with Next.js by jabx_fx',
    liveLink: '#',
    caseLink: '#',
    metrics: { label: '+110% session time', highlight: false },
    featured: false,
    size: 'normal',
  },
];
